### ISSUE TITLE
Facing Calibration issue with opencv==4.6.0

### ISSUE THREAD

**Issue by siddheshgunjal** [louisgeisler/BiIllard#2]
After I upgraded openCV version from 3.4.* to 4.6.0 to resolve earlier issue, I'm now facing then below issue while calibrating. Calibration worked fine with 3.4.* version but in 4.6.0, it is giving below error:
![Screenshot 2022-07-20 144545](https://user-images.githubusercontent.com/37741186/179958336-f40338aa-5b36-44b9-b4eb-5f273a24307a.png)

It is giving bad argument error for `cv2.line()` function in 4.6.0. but its working fine with 3.4.* .

Any suggestions to resolve this issue?

**Comment by siddheshgunjal** [comment]
This issue has been resolved by using opencv-python==4.5.1.48 .

**Comment by louisgeisler** [comment]
Hi @siddheshgunjal, thank you for your interest in my project. As it was my very first repo, I didn't think of including requierements.

However, it should now be fixed, and I also update some script to make them fully compatible with recent libraries.
So, let me know if it fully works, and if you have any other question, feel free to ask 👍
